name: Build & Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Create Git Tag
      uses: mathieudutour/github-tag-action@v6.2
      id: create_tag
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: patch
        tag_prefix: v
        release_branches: master,main
        create_annotated_tag: false
        fetch_all_tags: false
        dry_run: false

    - name: Print New Tag
      if: steps.create_tag.outputs.new_tag != ''
      run: |
        echo "New Tag: ${{ steps.create_tag.outputs.new_tag }}"

    - name: Set up Go
      uses: actions/setup-go@v5.3.0
      with:
        go-version: '1.22.11'

    - name: Initialize Go module and install dependencies
      run: |
        if [ ! -f go.mod ]; then
          go mod init docker-exporter
        fi
        go mod tidy

    - name: Build binary
      run: |
        CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o docker_exporter .

    - name: Create and Upload Release
      if: steps.create_tag.outputs.new_tag != ''
      uses: softprops/action-gh-release@v2.2.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.new_tag }}
        name: "Release ${{ steps.create_tag.outputs.new_tag }}"
        draft: false
        prerelease: false
        files: docker_exporter
